name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Golang Action
        uses: strongishllama/golang-action@main
        with:
          example-input: Hello world!
